apiVersion: v2
name: config
<<<<<<< HEAD
version: 1.8.90
appVersion: 1.8.90
=======
version: 1.8.0
appVersion: 1.8.0
tillerVersion: ">=2.7.2"
>>>>>>> f455c7e69... Prepare for release v1.8.0
description: Helm chart for Cilium configuration
keywords:
sources:
  - https://github.com/cilium/cilium
